### ISSUE TITLE
Adding ontology terms, some things I do not understand

### ISSUE THREAD

**Issue by Chris-Evelo** [enanomapper/tutorials#8]
"most ontologies include bits from other ontologies;" is given as a reason to not include full ontologies. This brings up the question why that is a problem. I suppose you mean to say that in that case you will take it from the source ontology if it is relevant in the first place. But ... would it not be relevant to also capture that it, in fact, occurs in both? Or is that something you would figure out elsewhere?

Under "Adding a terms from an already used ontology" (there is "a terms" must be a typo btw) it says:
"where in the eNanoMapper ontology should your selection show up?". That suggests it could show up under something that is not from that same (already used) ontology. Does that really make sense? Can you have 1) a branch that is below an existing branch from the same ontology but no longer connected via terms from that ontology (that feels strange, maybe, in that case, you should improve the source?) 2) have two branches used from an ontology but not use the part directly on top of both? That too feels strange, but I could imagine using wider terms at some stage, allowing the addition of parallel branches from other ontologies. I think that at least would need some review.

**Comment by egonw** [comment]
I just updated the tutorial taking into account these points. Moving things around should be done with care, of course. Peer review was part of eNanoMapper, but it less clearly defined right now. That said, we still have a gatekeeper and in today's WG F telcon someone from Birmingham will join who is interested on inconsistency detection in ontology to address this further (computer-aided-curation).
